spring:
  jpa:
    defer-datasource-initialization: true

#Application Configuration
server:
  error:
    include-message: always
    include-binding-errors: always

# To See H2 Console in Browser:
# http://localhost:8091/h2-console
# Enabling H2 Console
#spring:
#  h2:
#    console:
#      enabled: true
  # ===============================
  # DB
  # ===============================
  datasource:
    url: jdbc:postgresql://localhost/productDB
    driverClassName: org.postgresql.Driver
    platform: postgres
    username: postgres
    password: Duran2001

  # ===============================
  # JPA / HIBERNATE
  # ===============================
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    properties:
      hibernate:
        show_sql: true
        use_sql_comments: false
        format_sql: false
logging:
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} ${LOG_LEVEL_PATTERN:-%5p} %m%n"
