

spring:
  jpa:
    defer-datasource-initialization: true
  application:
    name: service-product
  cloud:
    config:
      uri: http://localhost:8080
      username: root
      password: Duran2001