
spring:
  cloud:
    config:
      server:
        git:  
          uri: https://github.com/JavierDuranFlores/Microservicios-Spring-Boot.git
          searchPaths: config-data
          username: ${GIT_USER}
          password: ${GIT_PASSWORD}
  security:
    user:
      name: root
      password: Duran2001
